spring:
  datasource:
    url: jdbc:mysql://localhost:3306/story_web
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: YOUR_FACEBOOK_APP_ID
            clientSecret: YOUR_FACEBOOK_APP_SECRET
            scope:
              - email
              - public_profile
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080

servlet:
  multipart:
    max-file-size: 10MB
    # dung lượng tối đa của request(tham số) mà người dùng truyền lên
    max-request-size: 10MB

jwt:
  privateKey: 17qJMfv76S8mAuBp5eDKS+P1L7ChJy6OytL96yTzFTc=

upload:
  path: C:\Users\admin\Desktop\HocJava\ThucHanhCuoiKhoa\Image

